import { mkdir, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { loadConfig } from '../lib/config.js';
import { log } from '../lib/logger.js';

const TYPE_OVERRIDES = {
  is_admin: 'boolean',
  is_guest: 'boolean',
  total_price: 'integer',
  legacy_user_id: 'integer',
  created_at: 'timestamptz',
  updated_at: 'timestamptz',
  migrated_at: 'timestamptz'
};

export async function createDatabaseAutomation() {
  const config = await loadConfig();
  const outputDir = process.env.APPNOW_DB_AUTOMATION_DIR ?? './database/automation';
  await mkdir(outputDir, { recursive: true });

  const migrationSql = renderMigration(config);
  const rlsSql = renderRls(config);
  const seedPlan = renderSeedPlan(config);

  await writeFile(join(outputDir, '001_create_tables.sql'), migrationSql, 'utf8');
  await writeFile(join(outputDir, '002_enable_rls.sql'), rlsSql, 'utf8');
  await writeFile(join(outputDir, 'seed-plan.md'), seedPlan, 'utf8');

  log.info(`Database automation written to ${outputDir}`);
}

function renderMigration(config) {
  return [
    '-- Generated by AppNow database automation.',
    '-- Review before running in Supabase SQL editor.',
    '',
    ...config.collections.flatMap((collection) => renderTable(collection)),
    ''
  ].join('\n');
}

function renderTable(collection) {
  const table = collection.supabaseTable ?? collection.name;
  const mapping = collection.mapping ?? {};
  const fields = Object.keys(mapping);
  const columns = new Set(['id', ...fields, 'migrated_at', 'migration_source']);

  const columnSql = [...columns].map((column) => {
    if (column === 'id') return '  id text primary key';
    return `  ${quoteIdentifier(column)} ${inferSqlType(column)}`;
  });

  return [
    `create table if not exists ${quoteIdentifier(table)} (`,
    columnSql.join(',\n'),
    ');',
    '',
    `create index if not exists ${quoteIdentifier(`${table}_migration_source_idx`)}`,
    `  on ${quoteIdentifier(table)} (migration_source);`,
    ''
  ];
}

function renderRls(config) {
  const lines = [
    '-- Generated by AppNow database automation.',
    '-- Starter RLS policies. Review before production use.',
    ''
  ];

  for (const collection of config.collections) {
    const table = collection.supabaseTable ?? collection.name;
    lines.push(`alter table ${quoteIdentifier(table)} enable row level security;`);
    lines.push('');
    lines.push(`drop policy if exists ${quoteIdentifier(`${table}_service_role_all`)} on ${quoteIdentifier(table)};`);
    lines.push(`create policy ${quoteIdentifier(`${table}_service_role_all`)}`);
    lines.push(`  on ${quoteIdentifier(table)}`);
    lines.push('  for all');
    lines.push('  using (auth.role() = \'service_role\')');
    lines.push('  with check (auth.role() = \'service_role\');');
    lines.push('');
  }

  return `${lines.join('\n')}\n`;
}

function renderSeedPlan(config) {
  const rows = config.collections.map((collection) => {
    const table = collection.supabaseTable ?? collection.name;
    return `| ${collection.name} | ${table} | ${collection.approval?.mode ?? 'default'} |`;
  });

  return `# AppNow Seed Plan

Generated database automation plan.

## Import Order

Use this order unless foreign keys are added manually:

${config.collections.map((collection, index) => `${index + 1}. ${collection.supabaseTable ?? collection.name}`).join('\n')}

## Collection Map

| Source | Supabase Table | Approval Mode |
| --- | --- | --- |
${rows.join('\n')}

## Notes

- Keep \`APPNOW_DRY_RUN=true\` until table SQL is reviewed.
- Run \`001_create_tables.sql\` first.
- Run \`002_enable_rls.sql\` after confirming service-role-only migration behavior.
- Add app-specific user-facing RLS policies later.
`;
}

function inferSqlType(column) {
  return TYPE_OVERRIDES[column] ?? 'text';
}

function quoteIdentifier(value) {
  return `"${String(value).replaceAll('"', '""')}"`;
}
