import { mkdir, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { loadConfig } from '../lib/config.js';
import { log } from '../lib/logger.js';

const TYPE_OVERRIDES = {
  is_admin: 'boolean',
  is_guest: 'boolean',
  total_price: 'integer',
  legacy_user_id: 'integer',
  created_at: 'timestamptz',
  updated_at: 'timestamptz',
  migrated_at: 'timestamptz'
};

export async function createDatabaseAutomation() {
  const config = await loadConfig();
  const outputDir = process.env.APPNOW_DB_AUTOMATION_DIR ?? './database/automation';
  await mkdir(outputDir, { recursive: true });

  const migrationSql = renderMigration(config);
  const rlsSql = renderRls(config);
  const seedPlan = renderSeedPlan(config);

  await writeFile(join(outputDir, '001_create_tables.sql'), migrationSql, 'utf8');
  await writeFile(join(outputDir, '002_enable_rls.sql'), rlsSql, 'utf8');
  await writeFile(join(outputDir, 'seed-plan.md'), seedPlan, 'utf8');

  log.info(`Database automation written to ${outputDir}`);
}

function renderMigration(config) {
  return [
    '-- Generated by AppNow database automation.',
    '-- Review before running in Supabase SQL editor.',
    '',
    'create extension if not exists pgcrypto;',
    '',
    ...config.collections.flatMap((collection) => renderTable(collection)),
    ...renderAppNowCoreTables(),
    ''
  ].join('\n');
}

function renderTable(collection) {
  const table = collection.supabaseTable ?? collection.name;
  const mapping = collection.mapping ?? {};
  const fields = Object.keys(mapping);
  const columns = new Set(['id', ...fields, 'migrated_at', 'migration_source']);

  const columnSql = [...columns].map((column) => {
    if (column === 'id') return '  id text primary key';
    return `  ${quoteIdentifier(column)} ${inferSqlType(column)}`;
  });

  return [
    `create table if not exists ${quoteIdentifier(table)} (`,
    columnSql.join(',\n'),
    ');',
    '',
    `create index if not exists ${quoteIdentifier(`${table}_migration_source_idx`)}`,
    `  on ${quoteIdentifier(table)} (migration_source);`,
    ''
  ];
}

function renderAppNowCoreTables() {
  return [
    '-- AppNow reusable backend core.',
    '',
    `create table if not exists "audit_logs" (`,
    '  id uuid primary key default gen_random_uuid(),',
    '  actor_id text,',
    '  table_name text not null,',
    '  row_id text not null,',
    '  action text not null,',
    '  patch jsonb,',
    '  created_at timestamptz not null default now()',
    ');',
    '',
    `create index if not exists "audit_logs_table_row_idx"`,
    '  on "audit_logs" (table_name, row_id);',
    '',
    `create table if not exists "catalog_categories" (`,
    '  id uuid primary key default gen_random_uuid(),',
    '  key text unique not null,',
    '  label text not null,',
    '  sort_order integer not null default 0,',
    '  metadata jsonb not null default \'{}\'::jsonb,',
    '  created_at timestamptz not null default now(),',
    '  updated_at timestamptz not null default now()',
    ');',
    '',
    `create table if not exists "service_types" (`,
    '  id uuid primary key default gen_random_uuid(),',
    '  category_id uuid references "catalog_categories"(id) on delete set null,',
    '  key text unique not null,',
    '  label text not null,',
    '  sort_order integer not null default 0,',
    '  metadata jsonb not null default \'{}\'::jsonb,',
    '  created_at timestamptz not null default now(),',
    '  updated_at timestamptz not null default now()',
    ');',
    '',
    `create table if not exists "pricing_tiers" (`,
    '  id uuid primary key default gen_random_uuid(),',
    '  service_type_id uuid references "service_types"(id) on delete cascade,',
    '  key text not null,',
    '  label text not null,',
    '  base_price integer not null default 0,',
    '  sort_order integer not null default 0,',
    '  metadata jsonb not null default \'{}\'::jsonb,',
    '  created_at timestamptz not null default now(),',
    '  updated_at timestamptz not null default now(),',
    '  unique(service_type_id, key)',
    ');',
    '',
    `create table if not exists "request_options" (`,
    '  id uuid primary key default gen_random_uuid(),',
    '  service_type_id uuid references "service_types"(id) on delete cascade,',
    '  key text not null,',
    '  label text not null,',
    '  extra_cost integer not null default 0,',
    '  sort_order integer not null default 0,',
    '  metadata jsonb not null default \'{}\'::jsonb,',
    '  created_at timestamptz not null default now(),',
    '  updated_at timestamptz not null default now(),',
    '  unique(service_type_id, key)',
    ');',
    '',
    `create table if not exists "requests" (`,
    '  id uuid primary key default gen_random_uuid(),',
    '  user_id text not null,',
    '  legacy_user_id integer,',
    '  category_id text,',
    '  service_type_id text,',
    '  subtype_id text,',
    '  pricing_tier_id text,',
    '  option_ids jsonb not null default \'[]\'::jsonb,',
    '  name text not null,',
    '  phone text,',
    '  address text,',
    '  detail_address text,',
    '  symptom text,',
    '  memo text,',
    '  reservation_date date not null,',
    '  reservation_time text not null,',
    '  timezone text not null default \'Asia/Seoul\',',
    '  status text not null default \'pending\',',
    '  total_price integer not null default 0,',
    '  legacy_id text,',
    '  migration_source text,',
    '  migrated_at timestamptz,',
    '  created_at timestamptz not null default now(),',
    '  updated_at timestamptz not null default now()',
    ');',
    '',
    `create unique index if not exists "requests_unique_active_slot_idx"`,
    '  on "requests" (reservation_date, reservation_time)',
    '  where status in (\'pending\', \'confirmed\', \'approved\');',
    '',
    `create index if not exists "requests_user_history_idx"`,
    '  on "requests" (user_id, reservation_date desc);',
    '',
    `create index if not exists "requests_status_date_idx"`,
    '  on "requests" (status, reservation_date);',
    ''
  ];
}

function renderRls(config) {
  const lines = [
    '-- Generated by AppNow database automation.',
    '-- Starter RLS policies. Review before production use.',
    ''
  ];

  for (const collection of config.collections) {
    const table = collection.supabaseTable ?? collection.name;
    lines.push(...renderServiceRolePolicy(table));
  }

  for (const table of ['audit_logs', 'catalog_categories', 'service_types', 'pricing_tiers', 'request_options', 'requests']) {
    lines.push(...renderServiceRolePolicy(table));
  }

  return `${lines.join('\n')}\n`;
}

function renderServiceRolePolicy(table) {
  return [
    `alter table ${quoteIdentifier(table)} enable row level security;`,
    '',
    `drop policy if exists ${quoteIdentifier(`${table}_service_role_all`)} on ${quoteIdentifier(table)};`,
    `create policy ${quoteIdentifier(`${table}_service_role_all`)}`,
    `  on ${quoteIdentifier(table)}`,
    '  for all',
    '  using (auth.role() = \'service_role\')',
    '  with check (auth.role() = \'service_role\');',
    ''
  ];
}

function renderSeedPlan(config) {
  const rows = config.collections.map((collection) => {
    const table = collection.supabaseTable ?? collection.name;
    return `| ${collection.name} | ${table} | ${collection.approval?.mode ?? 'default'} |`;
  });

  return `# AppNow Seed Plan

Generated database automation plan.

## Import Order

Use this order unless foreign keys are added manually:

${config.collections.map((collection, index) => `${index + 1}. ${collection.supabaseTable ?? collection.name}`).join('\n')}

## Collection Map

| Source | Supabase Table | Approval Mode |
| --- | --- | --- |
${rows.join('\n')}

## Notes

- Keep \`APPNOW_DRY_RUN=true\` until table SQL is reviewed.
- Run \`001_create_tables.sql\` first.
- Run \`002_enable_rls.sql\` after confirming service-role-only migration behavior.
- Add app-specific user-facing RLS policies later.
- The reusable service-booking core creates \`requests\`, catalog tables, \`request_options\`, \`pricing_tiers\`, and \`audit_logs\`.
- The generated \`requests_unique_active_slot_idx\` prevents double booking for active request statuses.
`;
}

function inferSqlType(column) {
  return TYPE_OVERRIDES[column] ?? 'text';
}

function quoteIdentifier(value) {
  return `"${String(value).replaceAll('"', '""')}"`;
}
