-- Generated by AppNow database automation.
-- Review before running in Supabase SQL editor.

create table if not exists "users" (
  id text primary key,
  "legacy_user_id" integer,
  "name" text,
  "phone" text,
  "email" text,
  "provider" text,
  "is_admin" boolean,
  "created_at" timestamptz,
  "migrated_at" timestamptz,
  "migration_source" text
);

create index if not exists "users_migration_source_idx"
  on "users" (migration_source);

create table if not exists "bookings" (
  id text primary key,
  "legacy_user_id" integer,
  "name" text,
  "reservation_date" text,
  "reservation_time" text,
  "status" text,
  "total_price" integer,
  "created_at" timestamptz,
  "migrated_at" timestamptz,
  "migration_source" text
);

create index if not exists "bookings_migration_source_idx"
  on "bookings" (migration_source);

