-- Generated by AppNow database automation.
-- Review before running in Supabase SQL editor.

create extension if not exists pgcrypto;

create table if not exists "users" (
  id text primary key,
  "legacy_user_id" integer,
  "name" text,
  "phone" text,
  "email" text,
  "provider" text,
  "is_admin" boolean,
  "created_at" timestamptz,
  "migrated_at" timestamptz,
  "migration_source" text
);

create index if not exists "users_migration_source_idx"
  on "users" (migration_source);

create table if not exists "bookings" (
  id text primary key,
  "legacy_user_id" integer,
  "name" text,
  "reservation_date" text,
  "reservation_time" text,
  "status" text,
  "total_price" integer,
  "created_at" timestamptz,
  "migrated_at" timestamptz,
  "migration_source" text
);

create index if not exists "bookings_migration_source_idx"
  on "bookings" (migration_source);

-- AppNow reusable backend core.

create table if not exists "audit_logs" (
  id uuid primary key default gen_random_uuid(),
  actor_id text,
  table_name text not null,
  row_id text not null,
  action text not null,
  patch jsonb,
  created_at timestamptz not null default now()
);

create index if not exists "audit_logs_table_row_idx"
  on "audit_logs" (table_name, row_id);

create table if not exists "catalog_categories" (
  id uuid primary key default gen_random_uuid(),
  key text unique not null,
  label text not null,
  sort_order integer not null default 0,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists "service_types" (
  id uuid primary key default gen_random_uuid(),
  category_id uuid references "catalog_categories"(id) on delete set null,
  key text unique not null,
  label text not null,
  sort_order integer not null default 0,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists "pricing_tiers" (
  id uuid primary key default gen_random_uuid(),
  service_type_id uuid references "service_types"(id) on delete cascade,
  key text not null,
  label text not null,
  base_price integer not null default 0,
  sort_order integer not null default 0,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(service_type_id, key)
);

create table if not exists "request_options" (
  id uuid primary key default gen_random_uuid(),
  service_type_id uuid references "service_types"(id) on delete cascade,
  key text not null,
  label text not null,
  extra_cost integer not null default 0,
  sort_order integer not null default 0,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(service_type_id, key)
);

create table if not exists "requests" (
  id uuid primary key default gen_random_uuid(),
  user_id text not null,
  legacy_user_id integer,
  category_id text,
  service_type_id text,
  subtype_id text,
  pricing_tier_id text,
  option_ids jsonb not null default '[]'::jsonb,
  name text not null,
  phone text,
  address text,
  detail_address text,
  symptom text,
  memo text,
  reservation_date date not null,
  reservation_time text not null,
  timezone text not null default 'Asia/Seoul',
  status text not null default 'pending',
  total_price integer not null default 0,
  legacy_id text,
  migration_source text,
  migrated_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists "requests_unique_active_slot_idx"
  on "requests" (reservation_date, reservation_time)
  where status in ('pending', 'confirmed', 'approved');

create index if not exists "requests_user_history_idx"
  on "requests" (user_id, reservation_date desc);

create index if not exists "requests_status_date_idx"
  on "requests" (status, reservation_date);

