-- Generated by AppNow database automation.
-- Starter RLS policies. Review before production use.

alter table "users" enable row level security;

drop policy if exists "users_service_role_all" on "users";
create policy "users_service_role_all"
  on "users"
  for all
  using (auth.role() = 'service_role')
  with check (auth.role() = 'service_role');

alter table "bookings" enable row level security;

drop policy if exists "bookings_service_role_all" on "bookings";
create policy "bookings_service_role_all"
  on "bookings"
  for all
  using (auth.role() = 'service_role')
  with check (auth.role() = 'service_role');

